"""Cria as tabelas iniciais do projeto

Revision ID: 16fd0aac0bc2
Revises: 
Create Date: 2026-09-09 01:41:10.238871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16fd0aac0bc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('bdg_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bdg_name', sa.String(length=255), nullable=False),
    sa.Column('bdg_description', sa.Text(), nullable=True),
    sa.Column('bdg_rarity', postgresql.ENUM('common', 'rare', 'epic', 'legendary', name='badge_rarity'), nullable=False),
    sa.Column('bdg_criteria', postgresql.ENUM('xp_gained', 'tracks_completed', 'lessons_completed', 'right_answers', 'day_streak', 'tracks_created', 'missions_completed', name='badge_criteria'), nullable=False),
    sa.Column('bdg_criteria_value', sa.Integer(), nullable=False),
    sa.Column('bdg_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('bdg_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('bdg_deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bdg_id')
    )
    op.create_table('user',
    sa.Column('usr_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usr_email', sa.String(length=255), nullable=False),
    sa.Column('usr_name', sa.String(length=255), nullable=False),
    sa.Column('usr_password_hash', sa.String(length=255), nullable=False),
    sa.Column('usr_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usr_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usr_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('usr_deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email')
    )
    op.create_table('badge_progress',
    sa.Column('bpg_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bpg_user_id', sa.UUID(), nullable=False),
    sa.Column('bpg_badge_id', sa.UUID(), nullable=False),
    sa.Column('bpg_status', postgresql.ENUM('idle', 'in_progress', 'done', name='badge_progress_status'), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('bpg_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bpg_badge_id'], ['badge.bdg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bpg_user_id'], ['user.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bpg_id'),
    sa.UniqueConstraint('bpg_user_id', 'bpg_badge_id')
    )
    op.create_table('day_streak',
    sa.Column('dst_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dst_user_id', sa.UUID(), nullable=False),
    sa.Column('dst_value', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dst_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst_user_id'], ['user.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dst_id'),
    sa.UniqueConstraint('dst_user_id')
    )
    op.create_table('login',
    sa.Column('lgn_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lgn_user_id', sa.UUID(), nullable=False),
    sa.Column('lgn_date', sa.Date(), nullable=False),
    sa.Column('lgn_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lgn_user_id'], ['user.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lgn_id'),
    sa.UniqueConstraint('lgn_user_id', 'lgn_date')
    )
    op.create_table('track',
    sa.Column('trk_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trk_user_id', sa.UUID(), nullable=False),
    sa.Column('trk_title', sa.String(length=255), nullable=False),
    sa.Column('trk_description', sa.Text(), nullable=True),
    sa.Column('trk_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('trk_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('trk_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('trk_deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trk_user_id'], ['user.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trk_id')
    )
    op.create_table('step',
    sa.Column('stp_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stp_track_id', sa.UUID(), nullable=False),
    sa.Column('stp_level', postgresql.ENUM('beginner', 'intermediate', 'advanced', 'pro', name='step_level'), nullable=False),
    sa.Column('stp_title', sa.String(length=255), nullable=False),
    sa.Column('stp_status', postgresql.ENUM('idle', 'in_progress', 'done', name='step_status'), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('stp_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('stp_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('stp_deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stp_track_id'], ['track.trk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stp_id')
    )
    op.create_table('lesson',
    sa.Column('lsn_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lsn_step_id', sa.UUID(), nullable=False),
    sa.Column('lsn_title', sa.String(length=255), nullable=False),
    sa.Column('lsn_text', sa.Text(), nullable=False),
    sa.Column('lsn_status', postgresql.ENUM('idle', 'in_progress', 'done', name='lesson_status'), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('lsn_position', sa.Integer(), nullable=False),
    sa.Column('lsn_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lsn_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lsn_deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lsn_step_id'], ['step.stp_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lsn_id'),
    sa.UniqueConstraint('lsn_step_id', 'lsn_position')
    )
    op.create_table('mission',
    sa.Column('msn_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('msn_step_id', sa.UUID(), nullable=False),
    sa.Column('msn_title', sa.String(length=255), nullable=False),
    sa.Column('msn_difficulty', postgresql.ENUM('easy', 'medium', 'hard', 'very_hard', name='mission_difficulty'), nullable=False),
    sa.Column('msn_xp_reward', sa.Integer(), nullable=False),
    sa.Column('msn_criteria', postgresql.ENUM('number_of_lessons_completed', 'get_all_answer_right_in_a_lesson', 'complete_a_step', 'complete_a_track', 'number_of_steps_completed', 'get_all_answers_right', name='mission_criteria'), nullable=False),
    sa.Column('msn_criteria_value', sa.Integer(), nullable=False),
    sa.Column('msn_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('msn_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('msn_deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['msn_step_id'], ['step.stp_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('msn_id')
    )
    op.create_table('feedback',
    sa.Column('fbk_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fbk_lesson_id', sa.UUID(), nullable=False),
    sa.Column('fbk_user_id', sa.UUID(), nullable=False),
    sa.Column('fbk_text', sa.Text(), nullable=False),
    sa.Column('fbk_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fbk_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fbk_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fbk_deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fbk_lesson_id'], ['lesson.lsn_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fbk_user_id'], ['user.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fbk_id')
    )
    op.create_table('lesson_file',
    sa.Column('lsf_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lsf_lesson_id', sa.UUID(), nullable=False),
    sa.Column('lsf_path', sa.String(length=1024), nullable=False),
    sa.Column('lsf_file_type', postgresql.ENUM('audio', 'gif', 'image', name='lesson_file_type'), nullable=False),
    sa.Column('lsf_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lsf_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lsf_deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lsf_lesson_id'], ['lesson.lsn_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lsf_id')
    )
    op.create_table('mission_progress',
    sa.Column('mpg_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mpg_user_id', sa.UUID(), nullable=False),
    sa.Column('mpg_mission_id', sa.UUID(), nullable=False),
    sa.Column('mpg_status', postgresql.ENUM('idle', 'in_progress', 'done', name='mission_progress_status'), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('mpg_finished_in', sa.DateTime(), nullable=True),
    sa.Column('mpg_score', sa.Integer(), nullable=True),
    sa.Column('mpg_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mpg_mission_id'], ['mission.msn_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mpg_user_id'], ['user.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mpg_id'),
    sa.UniqueConstraint('mpg_user_id', 'mpg_mission_id')
    )
    op.create_table('quiz',
    sa.Column('qui_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('qui_lesson_id', sa.UUID(), nullable=False),
    sa.Column('qui_question', sa.Text(), nullable=False),
    sa.Column('qui_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('qui_is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('qui_deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qui_lesson_id'], ['lesson.lsn_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qui_id')
    )
    op.create_table('answer',
    sa.Column('ans_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ans_question_id', sa.UUID(), nullable=False),
    sa.Column('ans_user_id', sa.UUID(), nullable=False),
    sa.Column('ans_text', sa.Text(), nullable=False),
    sa.Column('ans_rate', postgresql.ENUM('good', 'perfect', 'wrong', 'almost_got_it', name='answer_rate'), nullable=False),
    sa.Column('ans_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ans_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ans_question_id'], ['quiz.qui_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ans_user_id'], ['user.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ans_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('quiz')
    op.drop_table('mission_progress')
    op.drop_table('lesson_file')
    op.drop_table('feedback')
    op.drop_table('mission')
    op.drop_table('lesson')
    op.drop_table('step')
    op.drop_table('track')
    op.drop_table('login')
    op.drop_table('day_streak')
    op.drop_table('badge_progress')
    op.drop_table('user')
    op.drop_table('badge')
    # ### end Alembic commands ###
