#!/usr/bin/env sh

echo
echo "🔍 Running lint (ruff)..."
uv run ruff check . --fix
if [ $? -ne 0 ]; then
	echo "❌ Lint failed. Commit aborted."
	exit 1
fi

echo
echo "🎨 Checking code formatting..."
uv run ruff format .
if [ $? -ne 0 ]; then
	echo "❌ Format failed."
	exit 1
fi

echo
echo "✅ All checks passed!"